Carbonable/carbon-protocol

README.md
scripts/deploy.sh
scripts/logging.sh
scripts/tools.sh

7 add script to deploy

---

src/interfaces/minter.cairo
src/mint/library.cairo
src/mint/minter.cairo
tests/integrations/library.cairo
tests/integrations/test_nominal_case.cairo
tests/units/test_minter.cairo

implement withdraw function

---

protostar.toml

Fix #34 according to latest protostar version.

💚 uptate protostar version in protostar.toml file

---

protostar.toml
src/yield/library.cairo
src/yield/yield_manager.cairo
tests/integrations/yield/test_nominal_case.cairo
tests/units/test_yield_manager.cairo

Initialize `YieldManager` smart contract.
The design of the yield system is not completely defined but we stated that we should initiate the implementation and go with multiple iterations. 
This PR introduces the new smart contract that will be responsible of handling the yield associated with the Project NFTs.

✨ init yield manager

---

src/interfaces/minter.cairo
src/mint/library.cairo
src/mint/minter.cairo
tests/integrations/library.cairo
tests/integrations/test_nominal_case.cairo
tests/units/test_minter.cairo

✨ implement decrease reserved supply feature

---

README.md
protostar.toml

📝 add readme missing step

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/devops.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/new-feature.md
.github/ISSUE_TEMPLATE/refactor.md
.github/carbonable_labels.json
.github/github-project-setup.md

Add config files for Issues Template and Issues Labels

---

.github/workflows/test.yml

👷 add option to fix protostar version in CI

---

docs/SUMMARY.md

if docs/SUMMARY.md is generated, it should be fixed on the generation part.

fix typo (Externals instead of Exernals)

---

.gitmodules
protostar.toml
src/interfaces/starkvest.cairo
src/vesting/starkvest.cairo
tests/integrations/protocol/library.cairo

Fix #103 Adding Proxy support for starkvest contract

103 upgradable starkvest

---

src/offset/library.cairo
src/project/library.cairo
src/yield/library.cairo
tests/units/project/test_absorptions.cairo
tests/units/project/test_times.cairo

🐛 Fix failing views

---

.gitmodules
protostar.toml
src/interfaces/minter.cairo
src/interfaces/project.cairo
src/interfaces/vester.cairo
src/interfaces/yielder.cairo
src/mint/minter.cairo
src/project/project.cairo
src/utils/access/library.cairo
src/vesting/vester.cairo
src/yield/yielder.cairo
tests/config.yml
tests/integrations/protocol/library.cairo
tests/integrations/protocol/libs/admin.cairo
tests/integrations/protocol/libs/certifier.cairo
tests/integrations/protocol/libs/minter.cairo
tests/integrations/protocol/libs/project.cairo
tests/integrations/protocol/libs/snapshoter.cairo
tests/integrations/protocol/libs/vester.cairo
tests/integrations/protocol/libs/withdrawer.cairo
tests/integrations/protocol/libs/yielder.cairo
tests/integrations/protocol/test_minter.cairo
tests/integrations/protocol/test_offseter.cairo
tests/integrations/protocol/test_yielder.cairo

Feat-access-control

---

assets/examples/001/metadata.json
assets/examples/001/token.json
assets/examples/002/metadata.json
assets/examples/002/token.json
assets/examples/003/metadata.json
assets/examples/003/token.json
assets/examples/004/metadata.json
assets/examples/004/token.json
assets/examples/005/metadata.json
assets/examples/005/token.json
assets/examples/006/metadata.json
assets/examples/006/token.json
assets/examples/007/metadata.json
assets/examples/007/token.json

🍱 Update testnet assets

---

assets/examples/001/metadata.json
assets/examples/001/token.json
assets/examples/002/metadata.json
assets/examples/002/token.json
assets/examples/003/metadata.json
assets/examples/003/token.json
assets/examples/004/metadata.json
assets/examples/004/token.json
assets/examples/005/metadata.json
assets/examples/005/token.json
assets/examples/006/metadata.json
assets/examples/006/token.json
assets/examples/007/metadata.json
assets/examples/007/token.json
assets/projects/003/json/metadata.json
assets/projects/003/json/token.json
assets/projects/004/json/metadata.json
assets/projects/004/json/token.json
assets/projects/005/json/metadata.json
assets/projects/005/json/token.json

🍱 Update manjarisoa names

---

src/interfaces/vester.cairo
src/vesting/library.cairo
src/vesting/vester.cairo
tests/integrations/protocol/libs/anyone.cairo
tests/integrations/protocol/libs/vester.cairo
tests/integrations/protocol/test_yielder.cairo

✨ Add releasedOf view

---

README.md
docs/index.md
src/badge/badge.cairo
src/mint/library.cairo
src/mint/minter.cairo
src/vesting/vester.cairo
tests/units/minter/test_public_buy.cairo

Fix #145 
- Fix zero quantity issue
- Fix comments
- Fix missing decorator

🐛 Fix issues

---

assets/examples/001/metadata.json
assets/examples/001/token.json
assets/examples/002/metadata.json
assets/examples/002/token.json
assets/examples/003/metadata.json
assets/examples/003/token.json
assets/examples/004/metadata.json
assets/examples/004/token.json
assets/examples/005/metadata.json
assets/examples/005/token.json
assets/examples/006/metadata.json
assets/examples/006/token.json
assets/examples/007/metadata.json
assets/examples/007/token.json
assets/projects/001/json/metadata.json
assets/projects/001/json/token.json
assets/projects/002/json/metadata.json
assets/projects/002/json/token.json
assets/projects/003/json/metadata.json
assets/projects/003/json/token.json
assets/projects/004/json/metadata.json
assets/projects/004/json/token.json
assets/projects/005/json/metadata.json
assets/projects/005/json/token.json

🍱 Update mainnet and testnet metdata

---

src/interfaces/project.cairo
src/project/project.cairo
src/utils/access/library.cairo

⚡️ Update access control

---

src/interfaces/minter.cairo
src/mint/minter.cairo
tests/integrations/protocol/library.cairo
tests/integrations/protocol/libs/admin.cairo
tests/integrations/protocol/libs/anyone.cairo
tests/integrations/protocol/libs/minter.cairo

🐛 Fix issue

---

protostar.toml
src/mint/library.cairo
tests/units/minter/test_airdrop.cairo
tests/units/minter/test_pre_buy.cairo
tests/units/minter/test_public_buy.cairo
tests/units/minter/test_sold_out.cairo

🐛 Fix issue and add test

---

src/offset/library.cairo
tests/integrations/test_offseter.cairo
tests/units/offset/test_deposit.cairo
tests/units/offset/test_registration.cairo
tests/units/offset/test_total_absorption.cairo
tests/units/offset/test_total_claimable.cairo
tests/units/offset/test_total_claimed.cairo
tests/units/offset/test_withdraw.cairo
tests/units/yield/test_claim.cairo
tests/units/yield/test_provision.cairo
tests/units/yield/test_snapshot.cairo

Fix farming methods

---

.github/workflows/test.yml
.gitmodules
protostar.toml
src/offset/library.cairo
tests/integrations/test_offseter.cairo
tests/integrations/test_yielder.cairo
tests/units/offset/test_registration.cairo

Error overflow

---

Scarb.toml
src/components/metadata/interface.cairo
src/components/metadata/module.cairo
src/contracts/project.cairo
src/lib.cairo
src/tests/test_project.cairo

Feat: Add Metadata URIs component

---

src/components/metadata/interface.cairo
src/components/metadata/module.cairo
src/contracts/project.cairo

Feat: Add component provider

---

.github/workflows/build.yml
.github/workflows/test.yml
Scarb.toml
src/components/absorber/module.cairo
src/components/farm/module.cairo
src/tests/test_yielder.cairo

Fix: Testnet bugs

---

src/lib.cairo
src/tests/scenarios/test_iso_offseter_setting.cairo
src/tests/scenarios/test_iso_yielder_setting.cairo
src/tests/test_scenarios.cairo

:heavy_check_mark: Offsetter tests
:x:  Yielder tests

chore: [Farming tests] - Farming_deposit_and_withdraw (Offsetter)

---

src/tests/scenarios/test_iso_yielder_setting.cairo
src/tests/test_apr.cairo
src/tests/test_yielder.cairo

closes #291
- Added template for iso test to implement in another PR.

chore: [Farming test] Verify Cumsale in Yielder

---

src/tests/scenarios/test_iso_yielder_setting.cairo

chore: [Farming test] Price Config Accounting

---

src/components/absorber/interface.cairo
src/components/farm/interface.cairo
src/tests/scenarios/test_iso_yielder_setting.cairo
src/tests/test_yielder.cairo

mitigates #284 
Clarifying the behaviour of:
- `get_total_absorption`
- `get_max_absorption`
Need to cross-examine indexer https://github.com/Carbonable/carbonable-indexer-rs for consistency

Chore: [Doc] WIP contract interface docs

---

src/components/absorber/module.cairo
src/tests/scenarios/test_iso_yielder_setting.cairo

closes #288 
Beware, first test is very costly (14 billion gas)

chore: [test scenarios] Farming Reward Claims

---

scripts/deploy_minter.sh
scripts/deploy_offseter.sh
scripts/deploy_project.sh
scripts/deploy_yielder.sh
src/components/mint/interface.cairo
src/components/mint/module.cairo
src/contracts/minter.cairo
src/contracts/project.cairo
src/lib.cairo
src/tests/data.cairo
src/tests/scenarios/test_iso_karathuru.cairo
src/tests/scenarios/test_iso_las_delicias.cairo
src/tests/scenarios/test_iso_offseter_setting.cairo
src/tests/scenarios/test_iso_yielder_claims.cairo
src/tests/scenarios/test_iso_yielder_setting.cairo
src/tests/test_minter.cairo
src/tests/test_scenarios.cairo
src/tests/test_yielder.cairo

Quantity value variable

---

Scarb.toml
src/contracts/project.cairo
src/tests/test_project.cairo

Feat: Add ERC-2981

---

src/components/farm/module.cairo
src/components/mint/interface.cairo
src/components/mint/module.cairo
src/contracts/minter.cairo

Fix get remaining value and available 
